language: ruby
rvm:
  - 2.1.4
  - 2.2.3
  - 2.4.2

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.0"

script: bundle exec rspec

matrix:
  exclude:
    - rvm: 2.1.4
      env: RAILS_VERSION=5.0
